# Generated by Django 5.1.2 on 2024-10-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avarias',
            name='voltagem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
