# Generated by Django 5.1.2 on 2024-10-25 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0002_avarias_voltagem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avarias',
            new_name='Avaria',
        ),
    ]
