# Generated by Django 5.1.2 on 2024-10-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0003_rename_avarias_avaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaria',
            name='nf',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
