# Generated by Django 5.1.2 on 2025-01-07 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0005_brand_alter_avaria_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaria',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avarias/'),
        ),
        migrations.AlterField(
            model_name='avaria',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Avaria_brand', to='avarias.brand'),
        ),
    ]
