# Generated by Django 5.1.2 on 2025-01-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0006_avaria_photo_alter_avaria_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaria',
            old_name='photo',
            new_name='photo1',
        ),
        migrations.AddField(
            model_name='avaria',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='avarias/'),
        ),
    ]
