# Generated by Django 5.1.2 on 2025-03-11 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0007_rename_photo_avaria_photo1_avaria_photo2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaria',
            old_name='photo1',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='avaria',
            name='photo2',
        ),
    ]
