# Generated by Django 5.1.2 on 2025-03-19 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0008_rename_photo1_avaria_photo_remove_avaria_photo2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaria',
            name='photo',
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='avarias/')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imagens', to='avarias.avaria')),
            ],
        ),
    ]
