# Generated by Django 5.1.2 on 2025-03-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0010_imagem_delete_fotos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagem',
            new_name='Imagem_Avaria',
        ),
    ]
