# Generated by Django 5.1.2 on 2025-03-19 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0011_rename_imagem_imagem_avaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagem_avaria',
            old_name='photo',
            new_name='imagens',
        ),
    ]
