# Generated by Django 5.1.2 on 2025-03-19 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0012_rename_photo_imagem_avaria_imagens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagem_Avaria',
            new_name='Imagem',
        ),
    ]
