# Generated by Django 5.1.2 on 2025-03-19 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0013_rename_imagem_avaria_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagem',
            old_name='nome',
            new_name='avaria',
        ),
        migrations.RenameField(
            model_name='imagem',
            old_name='imagens',
            new_name='imagen',
        ),
    ]
