# Generated by Django 5.1.2 on 2025-03-19 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0014_rename_nome_imagem_avaria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagem',
            old_name='imagen',
            new_name='fotos',
        ),
    ]
