# Generated by Django 5.1.2 on 2025-03-19 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0016_avaria_photo_delete_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaria',
            name='photo',
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='avarias/', verbose_name='Arquivos')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='avarias.avaria')),
            ],
        ),
    ]
