# Generated by Django 5.1.2 on 2025-03-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0017_remove_avaria_photo_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaria',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avarias/'),
        ),
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
