# Generated by Django 5.1.2 on 2025-03-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0018_avaria_photo_delete_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvariaInvetory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avarias_count', models.IntegerField()),
                ('avarias_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
