# Generated by Django 5.1.2 on 2025-03-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0019_avariainvetory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvariaInvetory',
            new_name='AvariaInventory',
        ),
    ]
