# Generated by Django 5.1.2 on 2025-03-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0020_rename_avariainvetory_avariainventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaria',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
