# Generated by Django 5.1.2 on 2025-03-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0021_avaria_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaria',
            name='voltagem',
            field=models.CharField(choices=[('127', '127'), ('220', '220'), ('330', '330')], default='127', max_length=10),
        ),
    ]
