# Generated by Django 5.1.2 on 2025-03-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0022_alter_avaria_voltagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaria',
            name='voltagem',
            field=models.CharField(choices=[('127', '127'), ('220', '220'), ('SEM VOLTAGEM', 'SEM VOLTAGEM')], default='SEM VOLTAGEM', max_length=30),
        ),
    ]
