# Generated by Django 5.1.2 on 2025-03-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0023_alter_avaria_voltagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='industria',
        ),
    ]
