# Generated by Django 5.1.2 on 2025-03-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0024_rename_name_brand_industria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaria',
            name='voltagem',
            field=models.CharField(choices=[('127 VOLTS', '127 VOLTS'), ('220 VOLTS', '220 VOLTS'), ('SEM VOLTAGEM', 'SEM VOLTAGEM')], default='SEM VOLTAGEM', max_length=30),
        ),
    ]
