# Generated by Django 5.1.2 on 2025-03-26 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0025_alter_avaria_voltagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaria',
            old_name='nf',
            new_name='nota_fiscal',
        ),
    ]
