# Generated by Django 5.1.2 on 2025-03-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0026_rename_nf_avaria_nota_fiscal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaria',
            old_name='photo',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='avaria',
            old_name='brand',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='avaria',
            old_name='model',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='avaria',
            old_name='value',
            new_name='valor',
        ),
    ]
