# Generated by Django 5.1.2 on 2025-03-26 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0027_rename_photo_avaria_foto_rename_brand_avaria_marca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='avarias/', verbose_name='Imagens')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='avarias.avaria')),
            ],
        ),
    ]
