# Generated by Django 5.1.2 on 2025-03-26 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0028_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaria',
            name='foto',
        ),
    ]
