# Generated by Django 5.1.2 on 2025-03-26 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avarias', '0031_remove_avaria_foto_alter_imagemreferencia_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemreferencia',
            name='descricao',
        ),
    ]
